unbind C-b
set -g prefix C-[
bind C-[ send-prefix

# 設定ファイルのリロード
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# 256色表示
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'

# | でペインを縦に分割
bind | split-window -h
# 3 でペインを縦に分割
bind 3 split-window -h

# - でペインを横に分割
bind - split-window -v
# 2 でペインを横に分割
bind 2 split-window -v

# マウス操作
set -g mouse on

# ステータスバーの色を設定
set -g status-style 'fg=white, bg=black'

# その他ステータスラインの位置や更新間隔の設定
set -g status-position top
set -g status-interval 1

# ウィンドウリストの色を設定
set -g window-status-style 'fg=cyan, bg=default'
# アクティブなウィンドウを目立たせる
set -g window-status-current-style 'fg=white, bg=red, underscore'

# ESCの効きを良くする
set -s escape-time 0
