unbind C-b
set -g prefix C-t
bind C-t send-prefix

# 設定ファイルのリロード
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# 256色表示
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'

# スクロール可能行数の設定
set -g history-limit 100000

# windowの選択を M-0−9 に割り当て
bind M-1 selectw -t:=1
bind M-2 selectw -t:=2
bind M-3 selectw -t:=3
bind M-4 selectw -t:=4
bind M-5 selectw -t:=5
bind M-6 selectw -t:=6
bind M-7 selectw -t:=7
bind M-8 selectw -t:=8
bind M-9 selectw -t:=9
bind M-0 selectw -t:=0
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0

# | でペインを縦に分割（カレントディレクトリで開く）
bind | split-window -h -c '#{pane_current_path}'
# 3 でペインを縦に分割（カレントディレクトリで開く）
bind 3 split-window -h -c '#{pane_current_path}'

# - でペインを横に分割（カレントディレクトリで開く）
bind - split-window -v -c '#{pane_current_path}'
# 2 でペインを横に分割（カレントディレクトリで開く）
bind 2 split-window -v -c '#{pane_current_path}'

# window内の全ペインにカーソルを当てる
bind S set-window-option synchronize-panes

# マウス操作
set -g mouse on

# ステータスバーの色を設定
set -g status-style 'fg=white, bg=black'

# その他ステータスラインの位置や更新間隔の設定
set -g status-position top
set -g status-interval 1

# ステータスラインの右は時刻だけにする
set -g status-right '[%Y-%m-%d(%a) %H:%M]'

# ウィンドウリストの色を設定
set -g window-status-style 'fg=cyan, bg=default'
# アクティブなウィンドウを目立たせる
set -g window-status-current-style 'fg=white, bg=red, underscore'

# ESCの効きを良くする
set -s escape-time 0
