#!/usr/bin/env bash

set -e
set -u

if [ $# -ne 1 ]; then
   echo "Usage $0 [TARGET]"
   exit 0
fi

TARGET=$1

# FIXME: 検索が遅い
find . \
     -path ".git" -prune -o \
     -type d -name "build" -prune -o \
     -type f -print0 \
    | xargs -0 grep --color -I -n -i -E "${TARGET}"
